# Generated by Django 4.2 on 2025-05-21 13:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'verbose_name': 'Соединение', 'verbose_name_plural': 'Соединения'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='routestop',
            options={'ordering': ['route', 'order'], 'verbose_name': 'Маршрутная остановка', 'verbose_name_plural': 'Маршрутные остановки'},
        ),
        migrations.AlterModelOptions(
            name='stop',
            options={'verbose_name': 'Остановка', 'verbose_name_plural': 'Остановки'},
        ),
        migrations.AlterModelOptions(
            name='transporttype',
            options={'verbose_name': 'Тип транспорта', 'verbose_name_plural': 'Типы транспорта'},
        ),
        migrations.RemoveField(
            model_name='stop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='longitude',
        ),
        migrations.AddField(
            model_name='stop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Географическое положение'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='from_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_connections', to='project.stop', verbose_name='Остановка отправления'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='to_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_connections', to='project.stop', verbose_name='Остановка прибытия'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='travel_time',
            field=models.IntegerField(verbose_name='Время в пути (мин)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='transport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.transporttype', verbose_name='Тип транспорта'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядковый номер на маршруте'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.route', verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.stop', verbose_name='Остановка'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название остановки'),
        ),
        migrations.AlterField(
            model_name='transporttype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название типа транспорта'),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('from_stop', 'to_stop')},
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'order')},
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название проекта')),
                ('connections', models.ManyToManyField(blank=True, to='project.connection', verbose_name='Соединения')),
                ('route_stops', models.ManyToManyField(blank=True, to='project.routestop', verbose_name='Маршрутные остановки')),
                ('routes', models.ManyToManyField(blank=True, to='project.route', verbose_name='Маршруты')),
                ('stops', models.ManyToManyField(blank=True, to='project.stop', verbose_name='Остановки')),
                ('transport_types', models.ManyToManyField(blank=True, to='project.transporttype', verbose_name='Типы транспорта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
