# Generated by Django 4.2.23 on 2025-11-09 17:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_connection_options_alter_route_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gos_num', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Гос. номер')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Время')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Местоположение')),
                ('speed', models.PositiveIntegerField(default=0, verbose_name='Скорость')),
                ('direction', models.PositiveIntegerField(default=0, verbose_name='Направление (азимут)')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.route', verbose_name='Маршрут')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='project.vehicle', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Позиция ТС',
                'verbose_name_plural': 'Позиции ТС',
                'ordering': ['-timestamp'],
                'unique_together': {('vehicle', 'timestamp')},
            },
        ),
    ]
